# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'tasks' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Resolver'


  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'
  # Pods for tasks

  target 'tasksTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'tasksUITests' do
    # Pods for testing
  end

end
